rango/urls.py
# Handles remaining URL string after redirection
# from project URLs rango/

from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/',
         views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    # any url starting with rango/ is handled
    # by rango app
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ("name",)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ("category",)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if (url) and not (url.startswith('http://')):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render, redirect
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by("-views")[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict["pages"] = page_list
    visitor_cookie_handler(request)
    response = render(request, "rango/index.html", context=context_dict)
    return response


def about(request):
    visitor_cookie_handler(request)

    context_dict = {
        "boldmessage": "This tutorial has been put together by Vassilios.",
        "visits": request.session['visits']}
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
    else:
        print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                                category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    registered = False
    if (request.method == "POST"):
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if (user_form.is_valid() and profile_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if ("picture" in request.FILES):
                profile.picture = request.FILES["picture"]
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, "rango/register.html",
                  context={"user_form": user_form,
                           "profile_form": profile_form,
                           "registered": registered})


def user_login(request):
    if (request.method == "POST"):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse("rango:index"))
            else:
                return HttpResponse("Your rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, "rango/login.html")


@login_required
def restricted(request):
    return render(request, "rango/restricted.html")


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)

    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, "visits", '1'))
    last_visit_cookie = get_server_side_cookie(
        request, "last_visit", str(datetime.now()))
    last_visit_time = datetime.strptime(
        last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session["last_visit"] = str(datetime.now())
    else:
        request.session["last_visit"] = last_visit_cookie

    request.session["visits"] = visits

templates/rango/about.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page.<br />
        <strong>{{ boldmessage }}</strong><br />
    </div>
    <div>
        Visits: {{ visits }}
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /><br />
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>
{% endblock %}

templates/rango/add_category.html
{%extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <form id="category_form" method="post" action="/rango/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
{% endblock %}

templates/rango/add_page.html
{%extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>
    <div>
        <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
            {% csrf_token %}
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }} <br />
                {{ field.help_text }} <br />
                {{ field }}
            {% endfor %}
            <br /> <br />
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <title>
      Rango - 
      {% block title_block %} 
      How to Tango with Django! 
      {% endblock %}
    </title>
  </head>

  <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
    <hr />
    <div>
   <ul>
      {% if user.is_authenticated %}
        <!-- Show these links when the user is logged in -->
        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
        <li><a href="{% url 'rango:logout' %}">Logout</a></li>
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
      {% else %}
      <!-- Show these links when the user is NOT logged in -->
        <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
        <li><a href="{% url 'rango:login' %}">Login</a></li>
      {% endif %}
      <!-- Outside the conditional statements, ALWAYS show -->    
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
    </ul>
</div>
  </body>
</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else  %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul> 

templates/rango/category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
        {% else %}
            <strong>Log in to add a page</strong>
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
        <div>
           {% if user.is_authenticated %}
                howdy {{ user.username }}! <br />
            {% else %}
                hey there partner! <br />
            {% endif %}
            <strong>{{ boldmessage }}</strong><br />
        </div>

        <div>
            {% if categories %}
                <h2>Most Liked Categories</h2>
                <ul>
                    {% for category in categories %}
                        <li>
                            <a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>

        <div>
            {% if pages %}
                <h2>Most Viewed Pages</h2>
                <ul>
                    {% for page in pages %}
                    <li>
                        <a href="{{ page.url }}">{{ page.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>

        <div>
            <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        </div>
{% endblock %}

templates/rango/login.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/register.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %} 